---
- name: add docker apt key
  apt_key: id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88 url=https://download.docker.com/linux/debian/gpg

- name: add docker repoistory
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ansible_distribution_release}} stable"
    filename: docker

- name: install docker
  apt: name=docker-ce
